package movierecommendationsystem1;
import java.util.*;
import javax.swing.*;

public class MainFrame extends JFrame{

    private List<UserEntry> mainUsers;
    private List<UserEntry> targetUsers;
    private Map<Integer, String> movieTitles;
    private List<Integer> movieIds;
    private RecommendationEngine engine;
    private List<Integer> randomMovieIds;

    public MainFrame(){
        initComponents();

        loadData();
    }
    // Loads user, movie and recommendation data into the GUI
    private void loadData(){
        try{
            // Reads all users from CSV files
            mainUsers = DataLoader.loadUsers("data/main_data.csv");
            targetUsers = DataLoader.loadUsers("data/target_user.csv");
            // Loads movie titles and movie ids
            movieTitles = DataLoader.loadMovies("data/movies.csv");
            movieIds = DataLoader.getMovieIds("data/movies.csv");
            
            engine = new RecommendationEngine(mainUsers, movieTitles, movieIds);
            
            // Adds target users into combo box
            for(int i = 0; i < targetUsers.size(); i++){
                userComboBox.addItem("User " + targetUsers.get(i).userId);
            }

            // random movie list
            randomMovieIds = new ArrayList<>(movieIds);

               Collections.shuffle(randomMovieIds);

            randomMovieIds = randomMovieIds.subList(0, Math.min(10, randomMovieIds.size()));

            JComboBox<String>[] combos = new JComboBox[]{movieCombo1,movieCombo2,movieCombo3,movieCombo4,movieCombo5};
            // Fills combo boxes with movie titles
            for(int i = 0; i < combos.length; i++){
                for(int j = 0; j < randomMovieIds.size(); j++){
                    String title = movieTitles.getOrDefault(randomMovieIds.get(j),"Movie " + randomMovieIds.get(j));
                    combos[i].addItem(title );
                }
                combos[i].setSelectedIndex(i % randomMovieIds.size());
        }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Data loading error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        xField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kField1 = new javax.swing.JTextField();
        btnGetRec1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        movieCombo1 = new javax.swing.JComboBox<>();
        movieCombo2 = new javax.swing.JComboBox<>();
        movieCombo3 = new javax.swing.JComboBox<>();
        movieCombo4 = new javax.swing.JComboBox<>();
        movieCombo5 = new javax.swing.JComboBox<>();
        ratingField1 = new javax.swing.JTextField();
        ratingField2 = new javax.swing.JTextField();
        ratingField3 = new javax.swing.JTextField();
        ratingField4 = new javax.swing.JTextField();
        ratingField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        xField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kField2 = new javax.swing.JTextField();
        btnGetRec2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Target User:");

        jLabel2.setText("X :");

        jLabel3.setText("K:");

        btnGetRec1.setText("Get Recommendations");
        btnGetRec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRec1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(xField1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(btnGetRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(xField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetRec1))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        resultArea1.setEditable(false);
        resultArea1.setColumns(20);
        resultArea1.setRows(5);
        jScrollPane1.setViewportView(resultArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Target User Recommendation", jPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("X:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("K:");

        btnGetRec2.setText("Get Recommendations");
        btnGetRec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRec2ActionPerformed(evt);
            }
        });

        resultArea2.setEditable(false);
        resultArea2.setColumns(20);
        resultArea2.setRows(5);
        jScrollPane3.setViewportView(resultArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnGetRec2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movieCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movieCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ratingField5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(ratingField4)
                                    .addComponent(ratingField3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ratingField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ratingField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(xField2)
                                    .addComponent(kField2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addComponent(btnGetRec2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Movie Recommendation", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Generates movie recommendations according to selected target user
    private void btnGetRec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRec1ActionPerformed
        
        int selectedIndex = userComboBox.getSelectedIndex();
        int X, K;

        try{
            // Reads X and K values from text fields
            X = Integer.parseInt(xField1.getText());
            K = Integer.parseInt(kField1.getText());

        }catch(NumberFormatException ex){
            resultArea1.setText("X and K must be integers!");
            return;
        }

        UserEntry target = targetUsers.get(selectedIndex);
        List<String> recs = engine.getRecommendations(target.ratings,X,K);
        StringBuilder sb = new StringBuilder();
        sb.append("Recommendations:\n\n");
        // Adds recommended movies into result text
        for(int i = 0; i < recs.size(); i++){
            sb.append(i + 1).append(". ").append(recs.get(i)).append("\n");
        }
        // Shows message if no recommendation exists
        if(recs.isEmpty()){
            sb.append("No recommendations found.");
        }
        // Displays recommendations on GUI
        resultArea1.setText(sb.toString());
    }//GEN-LAST:event_btnGetRec1ActionPerformed
    // Generates recommendations according to selected movies and ratings
    private void btnGetRec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRec2ActionPerformed
        int X, K;

        try{
            // Reads X and K values from text fields
            X = Integer.parseInt(xField2.getText());
            K = Integer.parseInt(kField2.getText());
            
        }catch(NumberFormatException ex){
           resultArea2.setText("X and K must be integers!");
            return;
        }
        // Creates user rating vector
        double[] userVector = new double[movieIds.size()];
        // Stores selected movie ids to prevent duplicates
        Set<Integer> used = new HashSet<>();

        JComboBox<String>[] combos = new JComboBox[]{movieCombo1,movieCombo2,movieCombo3,movieCombo4,movieCombo5};
        JTextField[] ratingFs = new JTextField[]{ratingField1,ratingField2,ratingField3,ratingField4,ratingField5};
        // Reads selected movies and ratings
        for(int i = 0; i < 5; i++){
            int mid = randomMovieIds.get(combos[i].getSelectedIndex());
            // Checks whether the same movie is selected twice
            if(used.contains(mid)){
                resultArea2.setText("Please select 5 different movies!");
                return;
            }

            used.add(mid);
            int rating;

            try{
                // Reads rating value
                rating = Integer.parseInt(ratingFs[i].getText());

            }catch(NumberFormatException ex){
                resultArea2.setText("Rating must be an integer!");
                return;
            }
            // Checks rating range
            if(rating < 1 || rating > 5){
                resultArea2.setText("Rating must be between 1 and 5!");
                return;
            }
            // Places rating into correct movie index
            int idx = movieIds.indexOf(mid);
            if(idx >= 0){
                userVector[idx] = rating;
            }
        }
        // Gets recommendations from recommendation engine
        List<String> recs = engine.getRecommendations(userVector,X,K);
        StringBuilder sb = new StringBuilder();
        sb.append("Recommendations:\n\n");
        // Adds recommended movies into result text
        for(int i = 0; i < recs.size(); i++){
            sb.append(i + 1).append(". ").append(recs.get(i)).append("\n");
        }
        // Shows message if no recommendation exists
        if(recs.isEmpty()){
            sb.append("No recommendations found.");
        }
        // Displays recommendations on GUI
        resultArea2.setText(sb.toString());
    }//GEN-LAST:event_btnGetRec2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetRec1;
    private javax.swing.JButton btnGetRec2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kField1;
    private javax.swing.JTextField kField2;
    private javax.swing.JComboBox<String> movieCombo1;
    private javax.swing.JComboBox<String> movieCombo2;
    private javax.swing.JComboBox<String> movieCombo3;
    private javax.swing.JComboBox<String> movieCombo4;
    private javax.swing.JComboBox<String> movieCombo5;
    private javax.swing.JTextField ratingField1;
    private javax.swing.JTextField ratingField2;
    private javax.swing.JTextField ratingField3;
    private javax.swing.JTextField ratingField4;
    private javax.swing.JTextField ratingField5;
    private javax.swing.JTextArea resultArea1;
    private javax.swing.JTextArea resultArea2;
    private javax.swing.JComboBox<String> userComboBox;
    private javax.swing.JTextField xField1;
    private javax.swing.JTextField xField2;
    // End of variables declaration//GEN-END:variables
}
